Revert "Truncate database once before specs"
Fixes compile error:

```
In spec/setup/database.cr:8:22

 8 | BaseModel.database.truncate(restart_identity: false)
                        ^-------
Error: no parameter named 'restart_identity'
```

This reverts commit a1dabba3b5c4194f70b5b645185a2ed82fd151b3.