Fix compile error
```
Error: no overload matches 'UUID::Lucky.parse' with type Int64
```

Missed these in commit 4b003128ff9a3b4118dd5b5ad7ed3b2cc1db7979.